### ISSUE TITLE
登录QQ提示滑块验证请更换协议，换watch提示当前版本过低，要更新到 最新版

### ISSUE THREAD

**Issue by coderykw** [yyuueexxiinngg/cqhttp-mirai#148]
登录QQ提示滑块验证 请更换协议，换watch提示当前版本过低，要更新到 最新版，求解决办法 我有个号被冻结

**Comment by KingjZhang** [comment]
我下载运行最新0.3.4 版本，没有HTTP端口，好像登陆成功了。
```
2021-08-18 00:40:10 I/main: Starting mirai-console...
2021-08-18 00:40:10 I/main: Backend: version 2.0-RC, built on 2021-01-12 19:08:10.
2021-08-18 00:40:10 I/main: Frontend Terminal: version 2.0-RC, provided by Mamoe Technologies
2021-08-18 00:40:10 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-08-18 00:40:10 I/main: 0 plugin(s) enabled.
2021-08-18 00:40:10 I/main: mirai-console started successfully.
2021-08-18 00:40:10 I/OneBot: Plugin loaded! 0.3.4
2021-08-18 00:40:10 I/OneBot: 插件当前Commit 版本: 75a84ee
2021-08-18 00:40:12 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:132)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:57)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt$runMirai$1.invokeSuspend(Main.kt:91)
2021-08-18 00:40:12 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt.runMirai(Main.kt:89)
2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.OneBotKtCli.run(Main.kt:71)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt.main(Main.kt:78)
2021-08-18 00:40:12 W/stderr: Caused by: java.util.jar.JarException: file:/home/ubuntu/miraiqq/onebot-kotlin-0.3.4-all.jar has unsigned entries - META-INF/onebot-kotlin.kotlin_module
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:191)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:129)
2021-08-18 00:40:12 W/stderr: 	... 29 more
2021-08-18 00:40:12 I/Bot.2638818888: Logging in...
2021-08-18 00:40:12 I/Bot.2638818888: Online OtherClients: 
2021-08-18 00:40:13 I/Bot.2638818888: Login successful
```

**Comment by coderykw** [comment]
> 我下载运行最新0.3.4 版本，没有HTTP端口，好像登陆成功了。
> 
> ```
> 2021-08-18 00:40:10 I/main: Starting mirai-console...
> 2021-08-18 00:40:10 I/main: Backend: version 2.0-RC, built on 2021-01-12 19:08:10.
> 2021-08-18 00:40:10 I/main: Frontend Terminal: version 2.0-RC, provided by Mamoe Technologies
> 2021-08-18 00:40:10 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
> 2021-08-18 00:40:10 I/main: 0 plugin(s) enabled.
> 2021-08-18 00:40:10 I/main: mirai-console started successfully.
> 2021-08-18 00:40:10 I/OneBot: Plugin loaded! 0.3.4
> 2021-08-18 00:40:10 I/OneBot: 插件当前Commit 版本: 75a84ee
> 2021-08-18 00:40:12 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:132)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:57)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
> 2021-08-18 00:40:12 W/stderr: 	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt$runMirai$1.invokeSuspend(Main.kt:91)
> 2021-08-18 00:40:12 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
> 2021-08-18 00:40:12 W/stderr: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt.runMirai(Main.kt:89)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.OneBotKtCli.run(Main.kt:71)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
> 2021-08-18 00:40:12 W/stderr: 	at com.github.yyuueexxiinngg.onebot.MainKt.main(Main.kt:78)
> 2021-08-18 00:40:12 W/stderr: Caused by: java.util.jar.JarException: file:/home/ubuntu/miraiqq/onebot-kotlin-0.3.4-all.jar has unsigned entries - META-INF/onebot-kotlin.kotlin_module
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:191)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
> 2021-08-18 00:40:12 W/stderr: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:129)
> 2021-08-18 00:40:12 W/stderr: 	... 29 more
> 2021-08-18 00:40:12 I/Bot.2638818888: Logging in...
> 2021-08-18 00:40:12 I/Bot.2638818888: Online OtherClients: 
> 2021-08-18 00:40:13 I/Bot.2638818888: Login successful
> ```

你用本地 安卓跑的么

**Comment by KingjZhang** [comment]
不是,JAVA直接运行的
