### ISSUE TITLE
[BUG]onebot-mirai-0.3.4-all.jar报错导致机器人部分功能失效

### ISSUE THREAD

**Issue by Moon1995cn** [yyuueexxiinngg/cqhttp-mirai#165]
onebot-mirai-0.3.4-all.jar报错

```
[91m2022-07-10 00:04:21 W/rss-helper: Rss: https://rsshub.app/bilibili/live/room/5555734
java.lang.NoSuchMethodError: 'java.lang.Object io.ktor.client.call.HttpClientCall.receive(io.ktor.util.reflect.TypeInfo, kotlin.coroutines.Continuation)'
	at rss-helper-1.2.1.mirai.jar//io.github.gnuf0rce.rss.FeedKt$feed$2.invokeSuspend(Feed.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[91m2022-07-10 00:04:21 W/rss-helper: Rss: https://rsshub.app/bilibili/user/video/157761
java.lang.NoSuchMethodError: 'java.lang.Object io.ktor.client.call.HttpClientCall.receive(io.ktor.util.reflect.TypeInfo, kotlin.coroutines.Continuation)'
	at rss-helper-1.2.1.mirai.jar//io.github.gnuf0rce.rss.FeedKt$feed$2.invokeSuspend(Feed.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[91m2022-07-10 00:04:21 W/rss-helper: Rss: https://rsshub.app/ff14/zh/all
java.lang.NoSuchMethodError: 'java.lang.Object io.ktor.client.call.HttpClientCall.receive(io.ktor.util.reflect.TypeInfo, kotlin.coroutines.Continuation)'
	at rss-helper-1.2.1.mirai.jar//io.github.gnuf0rce.rss.FeedKt$feed$2.invokeSuspend(Feed.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[91m2022-07-10 00:04:22 W/rss-helper: Rss: https://rsshub.app/bilibili/live/room/5225
java.lang.NoSuchMethodError: 'java.lang.Object io.ktor.client.call.HttpClientCall.receive(io.ktor.util.reflect.TypeInfo, kotlin.coroutines.Continuation)'
	at rss-helper-1.2.1.mirai.jar//io.github.gnuf0rce.rss.FeedKt$feed$2.invokeSuspend(Feed.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[91m2022-07-10 00:04:22 W/rss-helper: Rss: https://rsshub.app/bilibili/live/room/94019
java.lang.NoSuchMethodError: 'java.lang.Object io.ktor.client.call.HttpClientCall.receive(io.ktor.util.reflect.TypeInfo, kotlin.coroutines.Continuation)'
	at rss-helper-1.2.1.mirai.jar//io.github.gnuf0rce.rss.FeedKt$feed$2.invokeSuspend(Feed.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at onebot-mirai-0.3.4-all.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


```

#### 复现

1.使用https://github.com/cssxsh/arknights-helper/releases
2.或者使用https://github.com/gnuf0rce/rss-helper/releases,然后随意测试一个订阅任务

#### 版本
onebot-` `- ` ` 

mirai-core-` `   
2.12
mirai-console-` `
2.12

**Comment by fatinghenji** [comment]
参考下这里？[在更新至2.12.0后部分插件报错](https://github.com/mamoe/mirai/issues/2146)
