### ISSUE TITLE
配置文件为空时报错

### ISSUE THREAD

**Issue by zhzRedstone** [yyuueexxiinngg/cqhttp-mirai#20]
log: 
```
[21:06:53.1464] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[21:06:53.1464] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[21:06:53.4755] I JRE: java version "1.8.0_231"
[21:06:53.4755] I JRE: Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
[21:06:53.4755] I JRE: Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
[21:06:53.4755] I 删除.lastupdate来在下次强制检查更新
[21:06:53.4765] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under D:\CQP\Mirai
All additional libraries are located at D:\CQP\Mirai\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:D:\CQP\Mirai\content\mirai-core-qqandroid-1.1.3.jar
Console        :D:\CQP\Mirai\content\mirai-console-0.5.2.jar
Root           :D:\CQP\Mirai/
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under D:\CQP\Mirai
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
 21:06:54 [INFO] [Plugin Manager] 开始加载D:\CQP\Mirai/plugins/下的插件
 21:06:54 [INFO] [Plugin Manager] loading plugin CQHTTPMirai
 21:06:54 [INFO] [Plugin Manager] successfully loaded plugin CQHTTPMirai version 0.1.8 by yyuueexxiinngg
 21:06:54 [INFO] [Plugin Manager] Mirai to CoolQ HTTP API Plugin
 21:06:54 [INFO] [CQHTTPMirai] Plugin loaded! 0.1.8
 21:06:54 [INFO] [Plugin Manager] 加载了1个插件
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
 21:06:54 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
 21:06:54 [INFO] [Bot Login] login...
 21:06:57 [INFO] [BOT 3173857429] Logging in...
 21:06:57 [INFO] [NETWORK] Connected to server msfwifi.3g.qq.com:8080
 21:06:57 [INFO] [NETWORK] Send: wtlogin.login
 21:06:57 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 21:06:57 [INFO] [NETWORK] Login successful
 21:06:57 [INFO] [NETWORK] Send: StatSvc.register
 21:06:57 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 21:06:57 [INFO] [NETWORK] 开始加载好友信息
 21:06:57 [INFO] [NETWORK] 开始加载群组列表与群成员列表
 21:06:57 [INFO] [NETWORK] Send: friendlist.getFriendGroupList
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopListReqV2
 21:06:57 [INFO] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
 21:06:57 [INFO] [NETWORK] 正在加载好友列表 8/8
 21:06:57 [INFO] [NETWORK] 好友列表加载完成, 共 8个
 21:06:57 [INFO] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
 21:06:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 21:06:58 [INFO] [NETWORK] 群组列表与群成员加载完成, 共 13个
 21:06:58 [INFO] [NETWORK] Awaiting ConfigPushSvc.PushReq
 21:06:58 [INFO] [NETWORK] Syncing friend message history...
 21:06:58 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 21:06:58 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 21:06:58 [INFO] [BOT 3173857429] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 21:06:58 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 21:06:59 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 21:06:59 [INFO] [BOT 3173857429] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 21:06:59 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 21:06:59 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 21:06:59 [INFO] [BOT 3173857429] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 21:06:59 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 21:06:59 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 21:06:59 [INFO] [NETWORK] Syncing friend message history: Success
 21:06:59 [INFO] [BOT 3173857429] [Maple Tavern ? Minecraft(330986863)] 萌 BadLee 新(1742594439) ->[mirai:source:1608076,80408718][mirai:quote:1608070,-965793259][mirai:at:564193464,@以Minecraft为载体的再演绎(cover)] [mirai:at:564193464,@以Minecraft为载体的再演绎(cover)] 建议直接武器A
 21:06:59 [INFO] [BOT 3173857429] Event processing: An exception occurred but no CoroutineExceptionHandler found,
                        either in coroutineContext from Handler job, or in subscriberContext
 21:06:59 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: 3173857429
        at net.mamoe.mirai.console.plugins.ConfigSection$DefaultImpls.getConfigSection(ConfigSection.kt:324)
        at net.mamoe.mirai.console.plugins.FileConfigImpl.getConfigSection(ConfigSection.kt:482)
        at tech.mihoyo.mirai.PluginBase$onEnable$1.invokeSuspend(PluginBase.kt:25)
        at tech.mihoyo.mirai.PluginBase$onEnable$1.invoke(PluginBase.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
		
 21:06:59 [INFO] [BOT 3173857429] Login successful
 21:06:59 [INFO] [Command] 3173857429 login successes
 21:07:00 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 21:07:00 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 21:07:00 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 21:07:00 [INFO] [NETWORK] ConfigPushSvc.PushReq: Success
 21:07:01 [INFO] [BOT 3173857429] [Maple Tavern ? Minecraft(330986863)] Lemon tree(1595862564) -> [mirai:source:1608077,1992608905]foreign fart
 21:07:03 [INFO] [BOT 3173857429] [FTS||FTS's?Circuit for survival(1033662023)] xli9527(1172326686)-> [mirai:source:28443,355435764]？？
 21:07:10 [INFO] [NETWORK] Send: OnlinePush.RespPush
```

纯属看着不舒服()

**Comment by yyuueexxiinngg** [comment]
啊, 我居然没这么测试过 (
