### ISSUE TITLE
发送消息时报错

### ISSUE THREAD

**Issue by zx900930** [yyuueexxiinngg/cqhttp-mirai#36]
发送消息时报错 
```
[ERROR] [CQHTTPMirai] java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:63)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

发送的String 为：
```
[喵萌奶茶屋&LoliHouse] 魔王学院的不适任者 / Maou Gakuin no Futekigousha - 06 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕]
【363.27 MB】| magnet:?xt=urn:btih:55baf2a5a25ddc9d608cb0064bf2c6ed42c87e10

[星空字幕组][魔王学院的不适合者～史上最强的魔王始祖，转生就读子孙们的学校～][05][简日双语][1080P][WEBrip][MP4]（急招翻译、校对）
【409.5MB】| magnet:?xt=urn:btih:4c8fb74d3374b3babd724a6cffebd17eca7203ec

[星空字幕组][魔王学院的不适合者～史上最强的魔王始祖，转生就读子孙们的学校～][05][繁日双语][1080P][WEBrip][MP4]（急招翻译、校对）
【409.5MB】| magnet:?xt=urn:btih:749e5935484fbc840858e10b220b08e48cc85754

【喵萌奶茶屋】★07月新番★[魔王学院的不适任者/Maou Gakuin no Futekigousha][06][1080p][繁体][招募翻译]
【425.22 MB】| magnet:?xt=urn:btih:153853a7847e997b1cf02b9ed5ec0f5c6cf6b065
```

同样的代码可以发送成功的String：
```
[Snow-Raws] 魔王勇者/Maoyuu Maou Yuusha/まおゆう魔王勇者 (BD 1920x1080 HEVC-YUV420P10 FLACx2)
【17.9GB】| magnet:?xt=urn:btih:3ca391337274bd405c1cb7c2fcadd741503379d4

[GM-Team][国漫][超兽武装 第2季 勇者无惧][Ultra Beast Force Ⅱ][2011][01-33 Fin][AVC][GB][1080P]
【15.4GB】| magnet:?xt=urn:btih:bc129563453bffac832c5f58f987db17d882863f

[Lilith-Raws] LAIDBACKERS：勇者的尼特族生活 / LAIDBACKERS [Baha][WEB-DL][1080p][AVC AAC][CHT][MKV]
【2.0GB】| magnet:?xt=urn:btih:4a904c313fce042f08b05254669a0e0dec6a2c7f

[SAIO-Raws] 盾之勇者成名录 第一季 Tate no Yuusha no Nariagari 1-25 [BD 1920x1080 HEVC-10bit OPUS][简繁内封字幕]
【13.6GB】| magnet:?xt=urn:btih:85c058bc4d385965d2ac78f5915219a6f6c64cc5
```
以及正常的返回信息：
`[INFO] [BOT xxxxxxxx] Friend(xxxxxxxxx) <- [Snow-Raws] 魔王勇者/Maoyuu Maou Yuusha/まおゆう魔王勇者 (BD 1920x1080 HEVC-YUV420P10 FLACx2)\n【17.9GB】| magnet:?xt=urn:btih:3ca391337274bd405c1cb7c2fcadd741503379d4\n\n[GM-Team][国漫][超兽武装 第2季 勇者无惧][Ultra Beast Force Ⅱ][2011][01-33 Fin][AVC][GB][1080P]\n【15.4GB】| magnet:?xt=urn:btih:bc129563453bffac832c5f58f987db17d882863f\n\n[Lilith-Raws] LAIDBACKERS：勇者的尼特族生活 / LAIDBACKERS [Baha][WEB-DL][1080p][AVC AAC][CHT][MKV]\n【2.0GB】| magnet:?xt=urn:btih:4a904c313fce042f08b05254669a0e0dec6a2c7f\n\n[SAIO-Raws] 盾之勇者成名录 第一季 Tate no Yuusha no Nariagari 1-25 [BD 1920x1080 HEVC-10bit OPUS][简繁内封字幕]\n【13.6GB】| magnet:?xt=urn:btih:85c058bc4d385965d2ac78f5915219a6f6c64cc5`

**Comment by yyuueexxiinngg** [comment]
Duplicate of #17

**Comment by zx900930** [comment]
@yyuueexxiinngg 群聊也不行, 不是长度的原因，比这个更长的都能发出来

**Comment by yyuueexxiinngg** [comment]
经测试, 例子中私聊无法发送的消息在群聊发送成功, 其长度为933 bytes, 私聊无法发出为正常现象, 例子中私聊成功发送的消息长度为752 bytes

即便不是消息长度的原因, 也与本项目无关, 请提交给`mirai`
