### ISSUE TITLE
HTTP API无法上报消息

### ISSUE THREAD

**Issue by ColorfulGhost** [yyuueexxiinngg/cqhttp-mirai#37]
``` 17:24:25 [DEBUG] [CQHTTPMirai] 收到上报响应  Oh hi there! How are you?
Exception in thread "DefaultDispatcher-worker-6" java.lang.IllegalStateException: Reader has not consumed the whole input: JsonReader(source='Oh hi there! How are you?', currentPosition=5, tokenClass=0, tokenPosition=3, offset=3)
        at kotlinx.serialization.json.Json.parse(Json.kt:132)
        at kotlinx.serialization.json.Json$Default.parse(Json.kt:210)
        at kotlinx.serialization.json.Json$Default.parseJson(Json.kt:231)
        at tech.mihoyo.mirai.web.http.ReportService.report(ReportService.kt:135)
        at tech.mihoyo.mirai.web.http.ReportService$report$1.invokeSuspend(ReportService.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

但是确实上报服务端收到了请求`[PicqBotX] [DEBUG(java.lang.Thread.run:748)] Http Failed: INCORRECT_CHARSET: Not UTF-8`

提示不是UTF-8

**Comment by yyuueexxiinngg** [comment]
猜测是`Header`里`Content-Type`没有设置`charset`的原因, 应该在新commit中已修复, 如测试无法使用请reopen
