### ISSUE TITLE
支持mirai-core 1.2.0？

### ISSUE THREAD

**Issue by zhzRedstone** [yyuueexxiinngg/cqhttp-mirai#45]
```log
[21:02:30.8037] I MiraiOK 20200629.160938 running at windows-amd64
[21:02:30.8037] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[21:02:30.8037] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[21:02:31.0810] I JRE: java version "1.8.0_231"
[21:02:31.0810] I JRE: Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
[21:02:31.0810] I JRE: Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
[21:02:31.0820] I 删除.lastupdate来在下次强制检查更新
[21:02:31.0820] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under D:\CQP\Mirai
All additional libraries are located at D:\CQP\Mirai\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:D:\CQP\Mirai\content\mirai-core-qqandroid-1.2.0.jar
Console        :D:\CQP\Mirai\content\mirai-console-0.5.2.jar
Root           :D:\CQP\Mirai/
 21:02:31 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under D:\CQP\Mirai
 21:02:31 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
 21:02:31 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 21:02:31 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
 21:02:32 [INFO] [Plugin Manager] 开始加载D:\CQP\Mirai/plugins/下的插件
 21:02:32 [INFO] [Plugin Manager] loading plugin CQHTTPMirai
 21:02:32 [ERROR] [Plugin Manager] failed to load plugin CQHTTPMirai , dependent class not found.
 21:02:32 [ERROR] [Plugin Manager] java.lang.NoClassDefFoundError: kotlinx/serialization/json/JsonException
        at tech.mihoyo.mirai.web.HttpApiServices.<init>(HttpApiServices.kt:9)
        at tech.mihoyo.mirai.PluginBase.<clinit>(PluginBase.kt:29)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
        at java.lang.reflect.Field.get(Field.java:393)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:116)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:241)
        at net.mamoe.mirai.console.plugins.PluginManager$loadPluginsImpl$3.invoke(PluginManager.kt:268)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPluginsImpl$mirai_console(PluginManager.kt:295)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:79)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins$default(PluginManager.kt:79)
        at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:131)
        at net.mamoe.mirai.console.MiraiConsole.start$default(MiraiConsole.kt:113)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.mamoe.mirai.console.wrapper.WrapperMain.start$mirai_console_wrapper(WrapperMain.kt:236)
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative$mirai_console_wrapper(WrapperMain.kt:207)
        at net.mamoe.mirai.console.wrapper.WrapperCli.run(WrapperMain.kt:143)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:176)
Caused by: java.lang.ClassNotFoundException: kotlinx.serialization.json.JsonException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 35 more

 21:02:32 [INFO] [Plugin Manager] 加载了0个插件
 21:02:32 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
 21:02:32 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
 21:02:32 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
```

**Comment by yyuueexxiinngg** [comment]
已支持，如急用可通过action下载，接下来将对console 1.0进行适配
