### ISSUE TITLE
求助 无法加载

### ISSUE THREAD

**Issue by jiangjiangflies** [yyuueexxiinngg/cqhttp-mirai#47]
Event processing: An exception occurred but no CoroutineExceptionHandler found,
                        either in coroutineContext from Handler job, or in subscriberContext
 18:30:56 [INFO] [NETWORK ERROR] java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at tech.mihoyo.mirai.web.http.HttpApiServerServiceConfig.<clinit>(HttpApiServerConfig.kt)
        at tech.mihoyo.mirai.web.http.HttpApiServer.<init>(HttpApiServer.kt:20)
        at tech.mihoyo.mirai.BotSession.<init>(Session.kt:62)
        at tech.mihoyo.mirai.SessionManager.createBotSession(Session.kt:29)
        at tech.mihoyo.mirai.PluginBase$onEnable$2.invokeSuspend(PluginBase.kt:60)
        at tech.mihoyo.mirai.PluginBase$onEnable$2.invoke(PluginBase.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by jiangjiangflies** [comment]
不知道什么原因，下载了以前的一个旧版本可以了。打扰
