### ISSUE TITLE
撤回他人消息时出错

### ISSUE THREAD

**Issue by ColorfulGhost** [yyuueexxiinngg/cqhttp-mirai#55]
```
 01:54:33 [DEBUG] [CQHTTPMirai] HTTP API response: {"status":"async","retcode":1,"data":null,"echo":null}
 01:54:33 [ERROR] [CQHTTPMirai] java.util.NoSuchElementException
        at tech.mihoyo.mirai.web.queue.CacheSourceQueue.get(CacheSourceQueue.kt:18)
        at tech.mihoyo.mirai.web.queue.CacheSourceQueue.get(CacheSourceQueue.kt:14)
        at tech.mihoyo.mirai.MiraiApi.cqDeleteMessage(MiraiApi.kt:138)
        at tech.mihoyo.mirai.MiraiApiKt.callMiraiApi(MiraiApi.kt:25)
        at tech.mihoyo.mirai.web.http.HttpApiModuleKt$cqHttpApiServer$1$$special$$inlined$cqHttpApi$10$2$1.invokeSuspend(HttpApiModule.kt:308)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


``` 
MiraiOK
版本：cqhttp-mirai-0.2.1-all .jar
框架：PicqBotX
调用撤回消息接口报错

**Comment by ColorfulGhost** [comment]
能否在控制台里加上消息ID，更新到最新版本撤回还是报错，我怀疑是不是找不到这个消息
![image](https://user-images.githubusercontent.com/11071219/91018084-b4cf1180-e621-11ea-94e7-b1eb1b1f3442.png)

**Comment by yyuueexxiinngg** [comment]
这个问题我一直无法复现, 报错是因为保存的列表中找不到消息发送回执, 但这个保存操作是在发送消息后就执行了的 

https://github.com/yyuueexxiinngg/cqhttp-mirai/blob/master/src/main/kotlin/tech/mihoyo/mirai/MiraiApi.kt#L114-L117

![image](https://user-images.githubusercontent.com/20928306/91125862-55323e00-e6d5-11ea-921a-bbd8efe21bd4.png)
![image](https://user-images.githubusercontent.com/20928306/91125904-69763b00-e6d5-11ea-854a-b45eb19d9f7c.png)

**Comment by rongzhongyang** [comment]
我碰到同样的问题。
mirai-core-qqandroid-1.2.2.jar
版本：cqhttp-mirai-0.2.3-all .jar
框架：Nonebot

**Comment by yyuueexxiinngg** [comment]
是否在尝试撤回他人消息？

**Comment by rongzhongyang** [comment]
是的。群消息撤回失败。2.1和2.3都是

**Comment by 1523789353** [comment]
撤回失败时aiohttp会报<retcode:103>


 翻阅大量CQhttp相关文档后了解到, 103 代表: [操作失败,一般是因为用户权限不足,或文件系统异常/不符合预期]



https://github.com/howmanybots/onebot/blob/master/legacy/API.md

**Comment by rongzhongyang** [comment]
谢谢！我已前用酷Q pro版时是可以撤回的。因为pro才有撤回功能。air版是没有的。会不会有可能是mirai没有撤回权限啊！QQ是有权限的，可以手动撤回。

**Comment by 1523789353** [comment]
按道理说mirai也能撤回啊

**Comment by yyuueexxiinngg** [comment]
可以撤回, 这是插件的BUG, 没有保存别人的消息导致找不到

**Comment by rongzhongyang** [comment]
是我的代码问题吗？我用的是nonebot。在代码中可以获取到消息ID，
if words in messageText:
                    try:
                        print("内容包含文字："+messageText)
                        await bot.delete_msg(message_id=ctx['message_id'])
                    except:
                        print("撤回消息失败！id:",ctx['message_id'])
能打印出消息ID

**Comment by 1523789353** [comment]
我也是,消息ID有,撤回不了


并且yobot和hoshino(nonebot)我都做了尝试

**Comment by ColorfulGhost** [comment]
> 可以撤回, 这是插件的BUG, 没有保存别人的消息导致找不到

dalao...不单单撤回他人消息报错 撤回自己的消息也报错.....

**Comment by 1523789353** [comment]
使用get_msg API也报retcode103，估计也和这个有关

**Comment by ColorfulGhost** [comment]
![image](https://user-images.githubusercontent.com/11071219/93811459-c3d9cb80-fc82-11ea-9e78-f8591f4d1f09.png)
调试出send_group_msg_async不返回message_id

**Comment by China-Uncle** [comment]
那么这个问题有解决方案了么大佬们

**Comment by China-Uncle** [comment]
> 可以撤回, 这是插件的BUG, 没有保存别人的消息导致找不到

请问，这个问题目前仍然没有解决方案嘛？

**Comment by ColorfulGhost** [comment]
> > 可以撤回, 这是插件的BUG, 没有保存别人的消息导致找不到
> 
> 请问，这个问题目前仍然没有解决方案嘛？

有个兼容方案.... 不知道适用于你那边否 
1. 在发送消息的时候不要使用异步API
2. 给messageId + 1

**Comment by China-Uncle** [comment]
> > > 可以撤回, 这是插件的BUG, 没有保存别人的消息导致找不到
> > 
> > 
> > 请问，这个问题目前仍然没有解决方案嘛？
> 
> 有个兼容方案.... 不知道适用于你那边否
> 
> 1. 在发送消息的时候不要使用异步API
> 2. 给messageId + 1

目前我这边可以撤回自己人发送的信息，无法撤回他人发布的信息
