### ISSUE TITLE
自己把自己挤下线..?

### ISSUE THREAD

**Issue by 1523789353** [yyuueexxiinngg/cqhttp-mirai#64]
同时存在config.txt登录配置与--account --password登录参数, 导致自己把自己挤下线..?

#### 版本
cqhttp-mirai- `0.2.2.5-embedded `

**Comment by 1523789353** [comment]
```[39;49m
[0m 09:19:59 [INFO] [NETWORK] Exception in NetworkHandler[39;49m
[0m 09:19:59 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10106
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:317)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:223)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:485)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:480)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:463)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[39;49m```
以上错误日志出现超过50次

**Comment by 1523789353** [comment]
以及修复一下Linux的文本染色符号(像  �[39;49m  ;  �[0m  ),我用的是Windows

**Comment by yyuueexxiinngg** [comment]
同账号多次登录这个会判断下, 染色符号为`mirai`那边提供的log方法带的, 请用`Windows Terminal`或新版`PowerShell`
