### ISSUE TITLE
[BUG] Event processing: An exception occurred but no CoroutineExceptionHandler found

### ISSUE THREAD

**Issue by PlexPt** [yyuueexxiinngg/cqhttp-mirai#65]
miraiOK 直接使用报的错
d

```
 [CQHTTPMirai] Exception in ReportService�[39;49m
�[0m 17:28:22 �[38;5;196m[ERROR]�[39;49m [CQHTTPMirai] io.ktor.client.features.ClientRequestException: Client request(http://xxxbaidu.com:2444/) invalid: 403 Forbidden
at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188)
at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31)
at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:80)
at tech.mihoyo.mirai.web.http.ReportService.report(ReportService.kt:202)
at tech.mihoyo.mirai.web.http.ReportService$report$1.invokeSuspend(ReportService.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### 版本
cqhttp-mirai- ` ` 
0.2.2.5

mirai-core-`1.2.2 `   
mirai-console-0.5.2

**Comment by ly1102** [comment]
这个问题和我的一样，你需要更新mirai-core，我凌晨提的issue，你可以去看看，是closed状态。

**Comment by PlexPt** [comment]
使用嵌入版则报

'''java
 [CQHTTPMirai] Exception in ReportService[39;49m
[0m 17:28:22 [38;5;196m[ERROR][39;49m [CQHTTPMirai] io.ktor.client.features.ClientRequestException: Client request(http://pt.fq.mk:2444/) invalid: 403 Forbidden
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31)
        at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:80)
        at tech.mihoyo.mirai.web.http.ReportService.report(ReportService.kt:202)
        at tech.mihoyo.mirai.web.http.ReportService$report$1.invokeSuspend(ReportService.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
'''

**Comment by yyuueexxiinngg** [comment]
此报错显示HTTP上报服务不被允许访问`http://xxxbaidu.com:2444/`, 请确认是否配置或服务器有问题?

**Comment by PlexPt** [comment]
> 此报错显示HTTP上报服务不被允许访问`http://xxxbaidu.com:2444/`, 请确认是否配置或服务器有问题?

@yyuueexxiinngg 
服务器无问题， 是今天酷q air重启挂了之后换这个， 配置原封不动的搬过来

**Comment by yyuueexxiinngg** [comment]
服务器的`访问log`可否给出? 使用的框架是什么呢?

**Comment by PlexPt** [comment]
现在是可以访问到，服务器可以正常收到消息，但回复收不到


---Original---

**Comment by yyuueexxiinngg** [comment]
有相关`log`吗? `CQHTTPMirai`的配置文件中`debug`改为`true`可打印debug日志

**Comment by PlexPt** [comment]
QQ group&nbsp;



---Original---

**Comment by PlexPt** [comment]
[PicqBotX] [DEBUG(java.lang.Thread.run:748)] Http Failed: INCORRECT_SHA1: Signature Empty

**Comment by yyuueexxiinngg** [comment]
请确认框架服务端是否配置了`secret`, 需在`CQHTTPMirai`中进行相同配置

**Comment by PlexPt** [comment]
原样照搬酷q的配置，也不行，服务端不管是否配置secret都无法收到回复。



---Original---

**Comment by PlexPt** [comment]
QQ加群通过一下



---Original---

**Comment by PlexPt** [comment]
@yyuueexxiinngg 打个包我试试
