### ISSUE TITLE
[Question]我也不知道是哪里的问题，显示网络错误

### ISSUE THREAD

**Issue by DancingSnow0517** [yyuueexxiinngg/cqhttp-mirai#73]
16:43:02 [INFO] [NETWORK ERROR] java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at tech.mihoyo.mirai.web.http.HttpApiServerServiceConfig.<clinit>(HttpApiServerConfig.kt)
        at tech.mihoyo.mirai.web.http.HttpApiServer.<init>(HttpApiServer.kt:20)
        at tech.mihoyo.mirai.BotSession.<init>(Session.kt:62)
        at tech.mihoyo.mirai.SessionManager.createBotSession(Session.kt:29)
        at tech.mihoyo.mirai.PluginBase$onEnable$2.invokeSuspend(PluginBase.kt:58)
        at tech.mihoyo.mirai.PluginBase$onEnable$2.invoke(PluginBase.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

在其他地方也接收不了信息了

**Comment by hy353** [comment]
我也是一样的问题。

**Comment by yyuueexxiinngg** [comment]
请问`mirai-console`及`mirai-core`的版本是?

**Comment by DancingSnow0517** [comment]
mirai-console是1.3.0，api是0.2.2.5-all

**Comment by DancingSnow0517** [comment]
插件有`cqhttp-mirai-0.2.2.5-all.jar` 和`mirai-native-1.8.6.jar`

**Comment by DancingSnow0517** [comment]
core是1.1.3的

**Comment by yyuueexxiinngg** [comment]
`cqhttp-mirai 0.2.2`以上版本需求`mirai-core`最低版本为`1.2.0`
