### ISSUE TITLE
[Question]2.1版本的能用。2.2和2.3的版本用不了。有人知道原因吗？

### ISSUE THREAD

**Issue by rongzhongyang** [yyuueexxiinngg/cqhttp-mirai#79]

**Comment by rongzhongyang** [comment]
12:31:27 [INFO] [Plugin Manager] loading plugin CQHTTPMirai
 12:31:28 [INFO] [Plugin Manager] successfully loaded plugin CQHTTPMirai version 0.2.3 by yyuueexxiinngg
 12:31:28 [INFO] [Plugin Manager] Mirai to CoolQ HTTP API Plugin
 12:31:28 [INFO] [Plugin Manager] loading plugin MiraiNative
 12:31:28 [INFO] [Plugin Manager] successfully loaded plugin MiraiNative version 1.8.2 by iTX Technologies
 12:31:28 [INFO] [Plugin Manager] 强大的 Mirai 原生插件加载器
 12:31:28 [INFO] [CQHTTPMirai] Plugin loaded! 0.2.3
 12:31:28 [INFO] [CQHTTPMirai] 插件当前Commit 版本: 3fd63ca
 12:31:28 [INFO] [Plugin Manager] java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at io.ktor.client.engine.okhttp.OkHttpEngine$clientCache$1.<init>(OkHttpEngine.kt)
        at io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:46)
        at io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:16)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:39)
        at tech.mihoyo.mirai.util.HttpClient.<clinit>(HttpClient.kt:15)
        at tech.mihoyo.mirai.PluginBase.onEnable(PluginBase.kt:46)
        at net.mamoe.mirai.console.plugins.PluginBase.enable$mirai_console(PluginBase.kt:144)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPluginsImpl$mirai_console(PluginManager.kt:334)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:79)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins$default(PluginManager.kt:79)
        at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:131)
        at net.mamoe.mirai.console.MiraiConsole.start$default(MiraiConsole.kt:113)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by rongzhongyang** [comment]
2.1版本的群消息撤回报错。看了文档，升级到2.2.5以上版本。都不能运行？是不是miraiOK运行环境问？请问作者你是在什么环境运行的？‘

**Comment by hy353** [comment]
mirai_core 的版本不对。2.1以上需要mirai_core1.22的版本。

**Comment by yyuueexxiinngg** [comment]
Duplicate of #73 #75 #62 #56 #47
