### ISSUE TITLE
[BUG]java.lang.Throwable: init or load class error

### ISSUE THREAD

**Issue by I-love-study** [yyuueexxiinngg/cqhttp-mirai#83]
在console-m3版本中无法启用插件

```
2020-08-30 15:26:43 I/main: Starting mirai-console...
2020-08-30 15:26:43 I/main: Backend: version 1.0-M3-1, built on 2020-08-27 22:43:41.
2020-08-30 15:26:43 I/main: Frontend Pure: version 1.0-M3-1, provided by Mamoe Technologies
2020-08-30 15:26:43 I/main: Reloading configurations...
2020-08-30 15:26:44 I/main: Prepared built-in commands: help, login, managers, stop
2020-08-30 15:26:44 I/main: Loading plugins...
2020-08-30 15:26:44 I/plugin: Cannot load plugin CQHTTPMirai
Exception in thread "main" java.lang.Throwable: init or load class error
        at net.mamoe.mirai.console.internal.plugin.PluginsLoader.loadPluginMainClassByJarFile(PluginsLoader.kt:67)
        at net.mamoe.mirai.console.internal.plugin.JarPluginLoaderImpl.load(JarPluginLoaderImpl.kt:87)
        at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt:35)
        at net.mamoe.mirai.console.plugin.DeferredPluginLoader.load(PluginLoader.kt:178)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:84)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAndEnableAllInOrder(PluginManagerImpl.kt:132)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadEnablePlugins$mirai_console(PluginManagerImpl.kt:127)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:102)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:118)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:53)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:52)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:40)
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/console/plugins/PluginBase
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.mamoe.mirai.console.internal.plugin.AdaptiveURLClassLoader.loadClass(PluginsLoader.kt:109)
        at net.mamoe.mirai.console.internal.plugin.PluginsLoader.loadPluginMainClassByJarFile(PluginsLoader.kt:60)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.plugins.PluginBase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 25 more
```

#### 复现

1.利用从miraiOK获取的jre启动mirai
`.\jre\bin\java.exe -cp ./content/* net.mamoe.mirai.console.pure.MiraiConsolePureLoader`

#### 版本
cqhttp-mirai- `0.2.3-all ` 

mirai-core-`mirai-core-qqandroid-1.2.2 `   

mirai-console-`mirai-console-1.0-M3-1 `

**Comment by yyuueexxiinngg** [comment]
暂不支持`console 1.0`, 等下一版,目前正在等`console 1.0`修BUG
