### ISSUE TITLE
新入群的人不会被get_group_member_info检测到，会报错

### ISSUE THREAD

**Issue by planevina** [yyuueexxiinngg/cqhttp-mirai#84]
客户端在运行期间新入群的人，机器人如果获取他的信息，就会报错
重启mirai客户端会就能正常运行
例如Hoshinobot里面的！入会，有个获取目标qq信息的函数，运行到那里就报错了，
重启客户端后再入会正常

mirai控制台出错信息
[0m 15:05:38 ← [38;5;196m[ERROR]← [39;49m [CQHTTPMirai] java.util.NoSuchElementException:  Member 14793xxxxx not found ingroup 69883xxxxxx
at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:277)
at tech.mihoyo.mirai.MiraiApi.cqGetGroupMemberInfo(MiraiApi.kt:325)
at tech.mihoyo.mirai.MiraiApiKt.callMiraiApi(MiraiApi.kt:54)
at tech.mihoyo.mirai.web.websocket.WebsocketActionsKt.handleWebSocketActions(WebsocketActions.kt28)
at tech.mihoyo.mirai.web.websocket.WebsocketReverseClient$listenApi$$inlined$consumeEach$lambda$1.invokeSuspend(WebcocketReverseClient.kt:204)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt :33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56>
at kotlinx.coroutines.scheduling.CoroutineScheduler. runSafely(CoroutineScheduler. kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask<CoroutineScheduler . kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker<CoroutineScheduler . kt :678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run <CoroutineScheduler - kt 665>

**Comment by yyuueexxiinngg** [comment]
请问`mirai-core`版本

https://github.com/mamoe/mirai/issues/518

**Comment by planevina** [comment]
就是用的您这个一体化的版本 cqhttp-mirai-0.2.3-embedded-all.jar

**Comment by yyuueexxiinngg** [comment]
是否是与此Issue有关
https://github.com/mamoe/mirai/issues/382

`get_group_member_info`中调用的是`mirai`的API, 应与本项目无关

**Comment by planevina** [comment]
好像就是那个Issue的问题，等mirai作者的新版本吧
