### ISSUE TITLE
使用 CQ:image 发送图片时出现错误 [Question]

### ISSUE THREAD

**Issue by Ice-Hazymoon** [yyuueexxiinngg/cqhttp-mirai#97]
```
[0m 19:57:20 [INFO] [BOT 2748164308] [~(117474650)] Ice-Hazymoon?(1733708055) -> [mirai:source:17921,536993175]/搜图[mirai:image:{00F47A9C-3DE3-450D-7CFF-B98118305F8E}.mirai][39;49m
[0m 19:57:26 [38;5;207m[DEBUG][39;49m [CQHTTPMirai] HTTP API response: {"status":"async","retcode":1,"data":null,"echo":null}[39;49m
[0m 19:57:26 [38;5;207m[DEBUG][39;49m [CQHTTPMirai] HTTP API Received: {"group_id":117474650,"message":"[CQ:at,qq=1733708055]
-------------------->
[CQ:image,file=file:///C:\Users\Administrator\Desktop\cqqbot\tmp\u8e7l3slr6s.png]
相似度：67.03%
https://www.pixiv.net/artworks/78171158","auto_escape":"false"}[39;49m
Exception in thread "DefaultDispatcher-worker-1" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 104: Invalid escaped char 'U'
JSON input: .....->
[CQ:image,file=file:///C:\Users\Administrator\Desktop\cqq.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:30)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329)
        at kotlinx.serialization.json.internal.JsonReader.appendEsc(JsonReader.kt:278)
        at kotlinx.serialization.json.internal.JsonReader.nextString(JsonReader.kt:249)
        at kotlinx.serialization.json.internal.JsonReader.nextToken(JsonReader.kt:213)
        at kotlinx.serialization.json.internal.JsonParser.readObject(JsonParser.kt:26)
        at kotlinx.serialization.json.internal.JsonParser.read(JsonParser.kt:82)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:37)
        at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:52)
        at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:30)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:62)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:40)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:113)
        at tech.mihoyo.mirai.web.http.HttpApiModuleKt.paramsToJson(HttpApiModule.kt:261)
        at tech.mihoyo.mirai.web.http.HttpApiModuleKt$cqHttpApiServer$1$$special$$inlined$cqHttpApi$6$1$1.invokeSuspend(HttpApiModule.kt:299)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m 19:57:33 [INFO] [NETWORK] Send: Heartbeat.Alive[39;49m
[0m 19:57:33 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response[39;49m
```

图片地址检查过是存在的，不知道是不是不支持 `[CQ:image,file=file:///C:\Users\Administrator\Desktop\cqqbot\tmp\u8e7l3slr6s.png]` 这种格式的CQ码

**Comment by yyuueexxiinngg** [comment]
上面使用文件时报的错是`json`格式不合法

下面这个不是很清楚, 可否附件给出发送的字符串进行测试
